### ISSUE TITLE
Can images be included in content?

### ISSUE THREAD

**Issue by Prague2049** [eyeinsky/org-anki#75] opened 2023-07-26 06:48 UTC
Can images be included in content? As follow:
* Test
:PROPERTIES:
:ANKI_NOTE_ID: 1690354020562
:END:
[[./img.png]]
Photos are not displayed in anki.

**Comment by eyeinsky** [comment] 2023-07-26 07:48
Syncing images is not supported at the moment :(. There feature is being worked on here #43, but it's not done yet.

**Comment by eyeinsky** [comment] 2023-08-25 08:44
I'm closing this as a duplicate of this issue: https://github.com/eyeinsky/org-anki/issues/17, let's discuss further there. :)

**Closed as completed by eyeinsky** 2023-08-25 08:44 UTC
